config/routes.rb
Rails.application.routes.draw do

  # Search articles
  get 'search' => 'search#show'
  
  # Archived articles
  get 'archives' => 'articles#archives'
  get 'archives/:page' => 'articles#archives'
  # Colophon
  get 'colophon' => 'articles#colophon'
    
  # XML-RPC for MarsEdit
  post 'xmlrpc' => 'xmlrpc#xe_index'
  
  # RSS Feed
  get 'feed' => 'articles#feed'
  get 'feed' => redirect("/feed.rss")

  # Article routes, this comes last on purpose
  resources :articles, path: ''
  root :to => 'articles#index'
  get ':friendly_id' => 'articles#show'
  
end

app/models/article.rb
## This is our Article class. It has a title, some text,
## and friendly id for url slugs. That's it!
class Article < ActiveRecord::Base
  extend FriendlyId

  validates :title, presence: true, uniqueness: true, length: { minimum: 5 }
  validates :text, presence: true

  serialize :title
  serialize :text
  friendly_id :title, use: :slugged

  def self.search(query)
    where('title like ? or text like ?', "%#{query}%", "%#{query}%")
  end
end

app/models/image.rb
## This is the Image class, it ties into paperclip for image upload
class Image < ActiveRecord::Base
  has_attached_file :attached_file,
                    styles: { large: '1000x1000>',
                              medium: '500x500>',
                              small: '200x200>',
                              thumb: '100x100>' }
  validates_attachment_content_type :attached_file,
                                    content_type: %r{\Aimage\/.*\Z}
end

app/models/user.rb
## This is the User class. It uses Rails' has_secure_password with bcrypt
## The app will allow any user to be an author, so choose users wisely!
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
## This is the application controller. The head honcho.
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
## This controller only handles showing articles and the feed.
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order('created_at DESC, updated_at DESC').first(3)
  end

  def archives
    page_size = 50

    @number_of_pages = (1.0 * Article.count / page_size).ceil.abs

    @page_number = archive_page_number(@number_of_pages)

    @articles = Article.all.order('created_at DESC, updated_at DESC')
    @articles = @articles.to_a.slice(page_size * (@page_number - 1), page_size)
  end

  def colophon
  end

  def show
    @article = Article.friendly.find(params[:id])
  end

  def feed
    @articles = Rails.cache.fetch("#{feed_cache_key}") do
      Article.all.order('created_at DESC, updated_at DESC')
    end

    respond_to do |format|
      format.html
      format.rss { render layout: false }
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  def archive_page_number(number_of_pages)
    page_number = params[:page].nil? ? 1 : params[:page].to_i.abs
    page_number = page_number > 0 ? page_number : 1
    [number_of_pages, page_number].min
  end

  def feed_cache_key
    count = Article.count
    max_updated_at = Article.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "articles/all-#{count}-#{max_updated_at}/feed"
  end
end

app/controllers/search_controller.rb
### This controller handles searching through the articles and displaying them
class SearchController < ApplicationController
  def show
    @search = params[:search]
    @articles = Article.search(@search).order('created_at DESC')
  end
end

app/controllers/xmlrpc_controller.rb
## This controller ties into the XMLRPC gem to let us implement metaWeblog
class XmlrpcController < ApplicationController
  
  # disabled to allow XMLRPC to connect
  protect_from_forgery except: :xe_index

  # XML-RPC for MarsEdit
  # We'll use camelCase instead of snake_case for method names
  # Because that is what metaWeblog expects
  exposes_xmlrpc_methods method_prefix: 'metaWeblog.'

  def getPost(postid, username, password)
    return unless User.find_by(name: username).try(:authenticate, password)
    article = Article.find(postid.to_i)
    hash = { title: article.title,
            description: article.text,
            link: Rails.application.secrets.app_url + '/'  + article.id.to_s,
            dateCreated: article.created_at.utc.iso8601,
            date_modified: article.updated_at.utc.iso8601,
            categories: '' }
    hash
  end
  
  def newPost(_blogid, username, password, content, _publish)
    return unless User.find_by(name: username).try(:authenticate, password)

	cover_image_url = nil
	html = Nokogiri::HTML.fragment(content['description'])
    unless html.nil? or html.css('img').nil? or html.css('img').first().nil?
    	cover_image_url = html.css('img').first().attribute('src').value
    end

    article = Article.new(title: content['title'],
                          text: content['description'],
                          cover_image_url: cover_image_url)

    return unless article.save
    article.id
  end

  def getRecentPosts(_blogid, username, password, number_of_articles)
    return unless User.find_by(name: username).try(:authenticate, password)
    number_of_articles ||= 10
    articles = Article.order('created_at DESC, updated_at DESC').limit(number_of_articles)
    arr = []
    articles.each do |article|
      hash = { postid: article.id.to_s,
        title: article.title,
        description: article.text,
        link: Rails.application.secrets.app_url + '/' + article.id.to_s,
        dateCreated: article.created_at.utc.iso8601,
        date_modified: article.updated_at.utc.iso8601,
        categories: '' }
      arr.push hash
    end

    arr
  end
  
  def editPost(postid, username, password, content, _publish)
    return unless User.find_by(name: username).try(:authenticate, password)
    
    cover_image_url = nil
	html = Nokogiri::HTML.fragment(content['description'])
    unless html.nil? or html.css('img').nil? or html.css('img').first().nil?
    	cover_image_url = html.css('img').first().attribute('src').value
    end
    
    Article.update(postid.to_i,
                    title: content['title'],
                    text: content['description'],
                    cover_image_url: cover_image_url)
    true
  end
    
  # Dave Winer's MetaWeblog does not define deletePost
  # We need to defer to the Blogger API it builds on
  # So we use blogger.deletePost instead of metaWeblog.deletePost
  # See: http://xmlrpc.scripting.com/metaWeblogApi.html
  add_method 'blogger.deletePost' do |_appkey, postid, username, password, _publish|
    return unless User.find_by(name: username).try(:authenticate, password)
    Article.delete(postid.to_i)
    true
  end
    
  def getCategories(_blogid, username, password)
    return unless User.find_by(name: username).try(:authenticate, password)
    
    # Categories are not available
    []
  end
  
  def newMediaObject(_blogid, username, password, data)
    return unless User.find_by(name: username).try(:authenticate, password)

    file_name = data['name'].to_s.split('/').last
    image = Image.new(name: file_name,
                      attached_file: StringIO.new(data['bits']))

    return unless image.save

    { file: image.attached_file_file_name,
      url: image.attached_file.url,
      type: image.attached_file_content_type }
  end
  
  def getUsersBlogs(_appkey, username, password)
    return unless User.find_by(name: username).try(:authenticate, password)

    [{ blogid: '1',
       url: Rails.application.secrets.app_url,
       blogName: 'Otters' }]
  end
end

app/helpers/application_helper.rb
## This is the application helper. Nothing to see here.
module ApplicationHelper
end

app/helpers/articles_helper.rb
## This is the articles helper. It only keeps the cache key for the views.
module ArticlesHelper
  def cache_key_for_articles
    count = Article.count
    max_updated_at = Article.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "articles/all-#{count}-#{max_updated_at}"
  end
end

app/helpers/search_helper.rb
## This is the search helper. Nothing to see here.
module SearchHelper
end

app/helpers/xmlrpc_helper.rb
## This is the xmlrpc helper. Nothing to see here.
module XmlrpcHelper
end

app/views/articles/archives.html.erb
<%= render 'partials/search_box', search: '' %>

<% cache(cache_key_for_articles) do %>
  <%= render 'partials/results', articles: @articles %>
<% end %>

<article class="center-align">
  <% if @page_number > 1 %>
    <strong>
      <%= link_to "← Newer Posts", "/archives/#{(@page_number - 1)}" %>
    </strong>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <% end %>
  
  <% if @page_number < @number_of_pages %>
    <strong>
      <%= link_to "Older Posts →", "/archives/#{(@page_number + 1)}" %>
    </strong>
  <% end %>
</article>

<%= render 'partials/selected_nav', selected: 'archives' %>

app/views/articles/colophon.html.erb
<article>
  <section class='article-text-container'>
    <br>
    <p>
    Otters.io is written by <a target='_blank' href='https://zaneswafford.com'>Zane Swafford</a>.
    </p>
    <br>
    <p>If you have trouble viewing this site in a modern browser, please let me know.</p>
    <br>
    <br>
    <p class='love'>Made with ❤ in Kansas</p>
  </section>
</article>

<%= render 'partials/selected_nav', selected: 'colophon' %>

app/views/articles/index.html.erb
<% cache(cache_key_for_articles) do %>
	<% @articles.each do |article| %>
		<article>
			<%= render 'partials/article_text_container', article: article %>
					
			<% if article != @articles.last %>
				<hr>
			<% else %>
				<br>
				<br>
				<br>
				<br>
			<% end %>
		</article>
	<% end %>
<% end %>

<%= render 'partials/selected_nav', selected: 'current' %>

app/views/articles/show.html.erb
<% content_for :head do %>
  <%= render 'partials/open_graph_meta_tags', article: @article %>
<% end %>
  
<% cache(@article) do %>
  <article class='active'>
    <%= render 'partials/article_text_container', article: @article %>
    <br>
    <br>
    <br>
  </article>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="description" content="An adorable little blog. One of those internet things about computers. Written by Zane Swafford.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Otters</title>
  <link rel="alternate" type="application/rss+xml" title="RSS" href="http://otters.io/feed.rss">
  <%= render 'partials/favicon' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="background_container">
  <header>
    <div id='logo_container'>
      <div id='title_container'>
        <%= image_tag 'logo.png' %>
        <h1>otters.io</h1>
        <small>An adorable little blog</small>
      </div>
    </div>
  </header>
  
    <div id="main">
      <nav>
        <ul>
          <li id='current'><%= link_to "Current", articles_path %></li>
          <li id='archives'><%= link_to "Archives", archives_path %></li>
          <li id='colophon'><%= link_to "Colophon", colophon_path %></li>
        </ul>
      </nav>
      
      <%= yield %>  
    </div>
  
  <footer>
    <div>
      <%= link_to "RSS", "feed.rss" %>
      <%= mail_to "zane@otters.io", "Email"%>
      <a href="https://twitter.com/ZaneSwafford" target="_blank">Twitter</a>
    </div>
    <small>© Otters <%= Time.now.year %></small>
  </footer>
  <%= render 'partials/analytics' %>
</div>
</body>
</html>

app/views/partials/_analytics.html.erb
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analytics.otters.io/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//analytics.otters.io/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->

app/views/partials/_archive.html.erb
<section class='article-text-container'>
  <%= truncate(strip_tags(article.text), length: 140)%>		
</section>

app/views/partials/_article_text_container.html.erb
<h1>
  <%= link_to article.title, article_path(article) %>
</h1>

<h2>
  <%= article.created_at.strftime("%A — %B #{article.created_at.day.ordinalize}, %Y") %>
</h2>

<section class='article-text-container'>
  <%= raw article.text %>		
</section>

app/views/partials/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/images/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/images/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/images/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/images/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/images/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/images/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/images/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/images/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/images/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/images/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/images/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/images/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/images/manifest.json">
<link rel="mask-icon" href="/images/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/images/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/images/mstile-144x144.png">
<meta name="msapplication-config" content="/images/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

app/views/partials/_open_graph_meta_tags.html.erb
<meta property="og:type" content="article" />
<meta property="og:url" content="https://otters.io/<%= article.slug %>" />
<meta property="og:title" content="<%= article.title %>" /> 
<% unless article.cover_image_url.nil? %>
  <meta property="og:image" content="https://otters.io<%= article.cover_image_url %>">
<% end %>

app/views/partials/_results.html.erb
<% articles.each do |article| %>
  <article>
    <h1><%= link_to article.title, article_path(article) %></h1>
    <h2><%= article.created_at.strftime("%A — %B #{article.created_at.day.ordinalize}, %Y") %></h2>

    <%= render 'partials/archive', article: article %>

    <% if article != articles.last %>
      <hr>
    <% else %>
      <br>
      <br>
      <br>
      <br>
    <% end %>
  </article>
<% end %>

app/views/partials/_search_box.html.erb
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:search, "Search for:") %>
  <%= text_field_tag(:search, search) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/partials/_selected_nav.html.erb
<script>
  var d = document.getElementById("<%= selected %>");
  d.className += " active";
</script>

app/views/search/show.html.erb
<%= render 'partials/search_box', search: @search %>

<%= render 'partials/results', articles: @articles %>

<%= render 'partials/selected_nav', selected: 'archives' %>